Einsums/Einsums

- src/include/einsums/Decomposition.hpp
- tests/CMakeLists.txt
- tests/Decomposition.cpp
This code allows the decomposition of an arbitrary dimensional tensor into a sum of outer products of vectors (called candecomp, or CP, decomposition)
(i.e. `X[i][j][k] = \sum_{r} (a[i][r] * b[j][r] * c[k][r]`)
> Implementation of CP Decomposition

- src/include/einsums/Decomposition.hpp
- tests/Decomposition.cpp
Implementation of the HO SVD (Higher-Order SVD) and HO-OI (Higher Order Orthogonal Inversion) approaches to the Tucker decomposition.
A general Tucker decomposition has the form:
`X(i, j, k) = G(p, q, r) * A(i, p) * B(j, q) * C(k, r)`
> Implement Tucker Decomposition

- src/include/einsums/Decomposition.hpp
- src/include/einsums/LinearAlgebra.hpp
Add a couple of features useful in my THC-CCSD(T) Code:
- Parallelization of rmsd/parafac_reconstruct functions (Decomposition.hpp)
- Add weighted_cp function, along with the ability to scale a tensor by first dimension (Decomposition.hpp)
- Add truncated_syev function (LinearAlgebra.hpp)
> New features from THC (T) code

- src/include/einsums/Decomposition.hpp
- tests/Decomposition.cpp
This PR has two purposes:
1.) Replace old, hacky khatri-rao code with khatri-rao function, and improve memory consumption in weighted CP
2.) Replace SVD with Diagonalization in initialize CP, improving memory consumption AND numerical stability
> CP Code Optimizations

- .github/workflows/cmake.yml
- CMakeLists.txt
- cmake/EinsumsConfig.cmake.in
- devtools/conda-envs/linux-dev.yml
- devtools/conda-envs/macos-dev.yml
- external/CMakeLists.txt
- src/CMakeLists.txt
> expand testing

- .github/workflows/cmake.yml
- CMakeLists.txt
- cmake/EinsumsAPI.cmake
- cmake/autocmake_safeguards.cmake
- external/CMakeLists.txt
- src/CMakeLists.txt
> intel compiler

- cmake/EinsumsAPIInternal.cmake
- cmake/EinsumsConfig.cmake.in
- cmake/FindCBLAS.cmake
- cmake/FindLAPACKE.cmake
- cmake/FindTargetLAPACK.cmake
- external/CMakeLists.txt
- external/catch2/CMakeLists.txt
- external/fmt/CMakeLists.txt
- external/h5cpp/CMakeLists.txt
- external/hptt/CMakeLists.txt
- external/netlib/CMakeLists.txt
- external/rangev3/CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
* all FC_Declare before any FC_MakeAvailable
* put each in its own dir so one can set variables to affect build w/o side effects (though variables need to be around FC_MakeAvailable, not FC_Declare, so I'm still not sure if it's right.
* after FC_MakeAvailable, any find_package finds it whether FC detected prebuilt or built from src, so introduce targets to the scope that needs them by later find_package calls, not by global scoping in the external/ dir.
```
If a project calls FetchContent_Declare():
◦ Add the FIND_PACKAGE_ARGS keyword if the dependency package meets the criteria for being consumed that way. If CMake versions earlier than 3.24 need to be supported, use a CMake version test to add it conditionally.
◦ Reserve OVERRIDE_FIND_PACKAGE for meeting strict requirements in …
```
> regularize external deps

- CMakeLists.txt
- THIRD-PARTY-LICENSES
- external/h5cpp/CMakeLists.txt
> add hptt and h5cpp licenses

- src/Blas.cpp
- src/backends/linear_algebra/vendor/Vendor.cpp
- src/include/einsums/Blas.hpp
- tests/TensorAlgebra.cpp
MKL doesn't follow the netlib reference standard for (c|z)dotu. We, therefore, implement our own version of it.
> Implement (z|c)dot ourselves.

- src/include/einsums/Tensor.hpp
- src/include/einsums/_Common.hpp
- tests/Tensor.cpp
1. First new feature is that you are no longer required to specify the Rank template parameter for the following struct.
Dim
Stride
Offset
Count
Chunk
They can be automatically deduced now by the compiler:
`Dim<2>{1, 2} -> Dim{1, 2}`
> Working on some new features.

- docs/source/reference/function.linear_algebra.rst
- src/include/einsums/LinearAlgebra.hpp
- tests/TensorAlgebra.cpp
Allows a dot product between a Tensor and TensorView.
Works for the test below, which is not added to the test suite but can be if deemed necessary
```
TEST_CASE("Dot TensorView and Tensor") {
using namespace einsums;
using namespace einsums::tensor_algebra;
using namespace einsums::tensor_algebra::index;
const auto i_ = 10, j_ = 10, k_ = 10, l_ = 2;
auto A  = create_random_tensor<double>("A", i_, k_);
auto B  = create_random_tensor<double>("B", k_, j_);
auto C  = create_tensor<double>("C", l_, j_);
auto C0  = create_tensor<double>("C0", l_, j_);
zero(C0);
auto A_view = A(Range{0, l_}, All); // (l_, k_)
einsum(Indices{l, j}, &C, Indices{l, k}, A_view, Indices{k, j}, B);
for (size_t l = 0; l < l_; l++) {
for (size_t j = 0; j < j_; j++) {
for (size_t k = 0; k < k_; k++) {
C0(l, j) += A(l, …
```
> Allow blas::dot between different Tensor types

- docs/source/reference/index.rst
Coverage report link was spelled coedcov, not codecov.
> Misspelled codecov link

- src/Timer.cpp
- src/include/einsums/BlockTensor.hpp
- src/include/einsums/Decomposition.hpp
- src/include/einsums/TiledTensor.hpp
Pushing to vectors can be slow if repeated due to repeated reallocations and copies. This pull reserves memory for vectors when applicable and when an upper bound is known. It also changes `TimerDetail` to use a deque instead of a vector for storing strings.
> Optimize some vector operations

- docs/source/reference/function.create.tensors.rst
- src/include/einsums/Tensor.hpp
- src/include/einsums/Utilities.hpp
- src/include/einsums/utility/IndexUtils.hpp
- tests/Tensor.cpp
Add a way to create a tensor view of a pointer. This is for compatibility with Psi4 shared matrices, but will also be useful with the Python compatibility layer.
> Add a way to create a tensor view of a pointer

- libs/Einsums/RuntimeConfiguration/src/RuntimeConfiguration.cpp
We need to let users specify their own command line arguments outside of einsums. Use `parse_known_args` instead of `parse_args` to do this.
> Fix parsing bug

- docs/sphinx/user/arguments.rst
- docs/sphinx/user/index.rst
- libs/Einsums/Config/include/Einsums/Config/CompilerSpecific.hpp
- libs/Einsums/Config/include/Einsums/Config/Types.hpp
- libs/Einsums/Config/src/Types.cpp
- libs/Einsums/Profile/src/Timer.cpp
- libs/Einsums/Runtime/include/Einsums/Runtime/ShutdownFunction.hpp
- libs/Einsums/Runtime/src/Finalize.cpp
- libs/Einsums/Runtime/src/InitLogging.cpp
- libs/Einsums/Runtime/src/InitRuntime.cpp
- libs/Einsums/Runtime/src/Runtime.cpp
- libs/Einsums/RuntimeConfiguration/include/Einsums/RuntimeConfiguration/RuntimeConfiguration.hpp
- libs/Einsums/RuntimeConfiguration/src/RuntimeConfiguration.cpp
- libs/Einsums/TypeSupport/include/Einsums/TypeSupport/Observable.hpp
- libs/EinsumsExperimental/modules.rst
- libs/EinsumsPy/modules.rst
- testing/testing/src/main.cpp
We have these global configuration maps, so why not use them for global options. The option keys are case insensitive, and dashes and underscores are considered to be the same. Also fixes a few memory leaks, some of which may be due to this change, others may have been stirred up from before.
> Put configuration options in global configuration maps

- libs/Einsums/Tensor/include/Einsums/Tensor/RuntimeTensor.hpp
- libs/Einsums/Tensor/tests/unit/CMakeLists.txt
- libs/Einsums/Tensor/tests/unit/RuntimeTensors.cpp
Added a way to wrap runtime tensors in compile-time views. Closes #113.
> Runtime views

- libs/Einsums/Concepts/CMakeLists.txt
- libs/Einsums/Concepts/include/Einsums/Concepts/NamedRequirements.hpp
- libs/Einsums/Concepts/src/CheckRequirements.cpp
- libs/Einsums/Config/include/Einsums/Config/CompilerSpecific.hpp
- libs/Einsums/LinearAlgebra/include/Einsums/LinearAlgebra/Base.hpp
- libs/Einsums/Tensor/include/Einsums/Tensor/Backends/DeviceTensor.hpp
- libs/Einsums/Tensor/include/Einsums/Tensor/BlockTensor.hpp
- libs/Einsums/Tensor/include/Einsums/Tensor/DeviceTensor.hpp
- libs/Einsums/Tensor/include/Einsums/Tensor/RuntimeTensor.hpp
- libs/Einsums/Tensor/include/Einsums/Tensor/Tensor.hpp
- libs/Einsums/Tensor/include/Einsums/Tensor/TensorForward.hpp
- libs/Einsums/Tensor/include/Einsums/Tensor/TiledTensor.hpp
- libs/Einsums/Tensor/src/TensorDefs.cpp
- libs/Einsums/Tensor/src/TensorDefs.hip
- libs/Einsums/Tensor/tests/unit/TensorView.cpp
- libs/Einsums/TensorAlgebra/include/Einsums/TensorAlgebra/Backends/ElementTransform.hpp
- libs/Einsums/TensorAlgebra/include/Einsums/TensorAlgebra/Backends/GenericAlgorithm.hpp
- libs/Einsums/TensorBase/include/Einsums/TensorBase/TensorBase.hpp
- libs/Einsums/TensorUtilities/include/Einsums/TensorUtilities/BlockViews.hpp
- libs/Einsums/TensorUtilities/tests/unit/BlockViews.cpp
- libs/Einsums/TensorUtilities/tests/unit/CMakeLists.txt
- libs/EinsumsPy/Tensor/include/EinsumsPy/Tensor/PyTensor.hpp
- libs/EinsumsPy/TensorAlgebra/include/EinsumsPy/TensorAlgebra/PyTensorAlgebra.hpp
This PR adds facilities to create views from block and tiled tensors where each member is viewed with a different range. This is intended to be used for doing `<pq|rs> -> <ia|jb>` transformations, where some indices are restricted in one way, and others in a different way.
> Add special view creation from block and tiled tensors

- libs/create_module_skeleton/ExportAll.cpp.in.fstring
- libs/create_module_skeleton/build_structure.py
- libs/create_module_skeleton/template_top/CMakeLists.txt.fstring
- libs/create_module_skeleton/template_top/src/InitModule.cpp.fstring
- libs/create_module_skeleton/template_top/src/InitModule.hpp.fstring
- libs/create_module_skeleton/template_top/src/ModuleVars.cpp.fstring
- libs/create_module_skeleton/template_top/src/ModuleVars.hpp.fstring
Fixes errors in the templates and in the build_struct.py file.
I also moved the InitModule.hpp and ModuleVars.hpp out of the public API headers into the private src directory. If it needs to be in the public API location then that can be handled on a case by case basis. But nothing in these headers are anything a user needs to use.
> CreateModuleSkeleton: Fix error in template and restructure it.

- libs/Einsums/TensorAlgebra/include/Einsums/TensorAlgebra/Detail/Index.hpp
- libs/Einsums/TensorAlgebra/tests/unit/Sort.cpp
Some users have had issues where they may unintentionally create a tensor with the same name as an index. This change will make it so that an error is thrown when users try to pass a tensor to the indices object.
> Make Indices only accept indices.

- cmake/Einsums_SetupCppTrace.cmake
- cmake/templates/EinsumsConfig.cmake.in
- devtools/conda-envs/merge_yml.py
- devtools/conda-envs/snippets/common.yml
- devtools/conda-envs/snippets/os/Darwin.yml
- devtools/conda-envs/snippets/os/Linux.yml
- devtools/conda-envs/snippets/os/Windows.yml
- libs/Einsums/StringUtil/tests/unit/CMakeLists.txt
Updates the Cpptrace dependency to the v1 release. Separately, I got macOS ARM conda builds of Cpptrace and its dependency libdwarf approved. This also updates the `devtool/conda-env` scripts.
> Updates cpptrace dependency.

- docs/sphinx/changelogs/v2/v2.0.0.rst
- libs/Einsums/LinearAlgebra/include/Einsums/LinearAlgebra.hpp
- libs/Einsums/LinearAlgebra/include/Einsums/LinearAlgebra/Base.hpp
- libs/Einsums/LinearAlgebra/tests/unit/norm.cpp
- libs/EinsumsPy/LinearAlgebra/src/Export.cpp
- tests/test_linalg.py
- tests/test_linalg_views.py
I don't know why, but LAPACK seems to lack the induced 2-norm for matrices. Perhaps because it can be calculated using `gesvd`. This fills out the main code path for the induced 2-norm. For types that are incompatible with LAPACK, which we don't fully support yet, the code path is empty. We can fill it out when we need it.
> Add the induced 2-norm
